// <auto-generated />
using DiShelved.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiShelved.Migrations
{
    [DbContext(typeof(DiShelvedDbContext))]
    partial class DiShelvedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiShelved.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A collection of board games.",
                            Name = "Board Games",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Warhammer 40k",
                            Name = "Miniatures",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Holiday Decorations",
                            Name = "Decorations",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("DiShelved.Models.Container", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Containers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A shelf for board games.",
                            LocationId = 1,
                            Name = "Game Shelf",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "A box for miniatures.",
                            LocationId = 2,
                            Name = "Miniature Box",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "A box for holiday decorations.",
                            LocationId = 3,
                            Name = "Holiday Box",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("DiShelved.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Complete")
                        .HasColumnType("boolean");

                    b.Property<int>("ContainerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Complete = true,
                            ContainerId = 1,
                            Description = "A board game.",
                            Image = "https://example.com/monopoly.jpg",
                            Name = "Monopoly",
                            Quantity = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Complete = false,
                            ContainerId = 1,
                            Description = "A second board game.",
                            Image = "https://example.com/parcheesi.jpg",
                            Name = "Parcheesi",
                            Quantity = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Complete = true,
                            ContainerId = 2,
                            Description = "Minitatures for Warhammer 40k.",
                            Image = "https://example.com/warhammer.jpg",
                            Name = "Space Marines",
                            Quantity = 12,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Complete = false,
                            ContainerId = 2,
                            Description = "Minitatures for Warhammer 40k.",
                            Image = "https://example.com/eldar.jpg",
                            Name = "Eldar Guardians",
                            Quantity = 10,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Complete = true,
                            ContainerId = 3,
                            Description = "A Christmas tree.",
                            Image = "https://example.com/christmas_tree.jpg",
                            Name = "Christmas Tree",
                            Quantity = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            Complete = false,
                            ContainerId = 3,
                            Description = "Decorations for Halloween.",
                            Image = "https://example.com/halloween.jpg",
                            Name = "Halloween Decorations",
                            Quantity = 1,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("DiShelved.Models.ItemCategory", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.HasKey("ItemId", "CategoryId");

                    b.ToTable("ItemCategories");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            ItemId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            ItemId = 3,
                            CategoryId = 2
                        },
                        new
                        {
                            ItemId = 4,
                            CategoryId = 2
                        },
                        new
                        {
                            ItemId = 5,
                            CategoryId = 3
                        },
                        new
                        {
                            ItemId = 6,
                            CategoryId = 3
                        });
                });

            modelBuilder.Entity("DiShelved.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The main living area of the house.",
                            Name = "Living Room",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "The garage where boxes are stored.",
                            Name = "Garage",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "The attic where old items are stored.",
                            Name = "Attic",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("DiShelved.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
